# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'register.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(500, 450)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Form.sizePolicy().hasHeightForWidth())
        Form.setSizePolicy(sizePolicy)
        Form.setMinimumSize(QtCore.QSize(500, 450))
        Form.setMaximumSize(QtCore.QSize(500, 450))
        Form.setStyleSheet("QWidget#Form {border-image: url(:/img/regist1.jpg)}")
        self.main_menu_btn = QtWidgets.QPushButton(Form)
        self.main_menu_btn.setGeometry(QtCore.QRect(30, 40, 51, 51))
        self.main_menu_btn.setStyleSheet("QPushButton  {\n"
"    border-radius: 25px;\n"
"    background-color:rgb(215, 255, 194);\n"
"    \n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: rgb(67, 99, 49);\n"
"    border-radius: 25px\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: rgb(215, 255, 194);\n"
"    color:rgb(255, 255, 255);\n"
"    border-radius: 25px\n"
"}\n"
"\n"
"QPushButton:checked {\n"
"    background-color: rgb(67, 99, 49);\n"
"    color:rgb(255, 255, 255);\n"
"    border-radius: 25px\n"
"}")
        self.main_menu_btn.setCheckable(True)
        self.main_menu_btn.setChecked(False)
        self.main_menu_btn.setObjectName("main_menu_btn")
        self.back_btn = QtWidgets.QPushButton(Form)
        self.back_btn.setGeometry(QtCore.QRect(20, 110, 51, 51))
        self.back_btn.setStyleSheet("QPushButton  {\n"
"    border-radius: 25px;\n"
"    background-color:rgb(215, 255, 194);\n"
"    \n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: rgb(67, 99, 49);\n"
"    border-radius: 25px\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: rgb(242, 255, 161);\n"
"    color:rgb(255, 255, 255);\n"
"    border-radius: 25px\n"
"}")
        self.back_btn.setCheckable(False)
        self.back_btn.setObjectName("back_btn")
        self.about_btn = QtWidgets.QPushButton(Form)
        self.about_btn.setGeometry(QtCore.QRect(90, 10, 51, 51))
        self.about_btn.setStyleSheet("QPushButton  {\n"
"    border-radius: 25px;\n"
"    background-color:rgb(215, 255, 194);\n"
"    \n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: rgb(67, 99, 49);\n"
"    border-radius: 25px\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: rgb(242, 255, 161);\n"
"    color:rgb(255, 255, 255);\n"
"    border-radius: 25px\n"
"}")
        self.about_btn.setCheckable(False)
        self.about_btn.setObjectName("about_btn")
        self.clear_btn = QtWidgets.QPushButton(Form)
        self.clear_btn.setGeometry(QtCore.QRect(90, 80, 51, 51))
        self.clear_btn.setStyleSheet("QPushButton  {\n"
"    border-radius: 25px;\n"
"    background-color:rgb(215, 255, 194);\n"
"    \n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: rgb(67, 99, 49);\n"
"    border-radius: 25px\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: rgb(242, 255, 161);\n"
"    color:rgb(255, 255, 255);\n"
"    border-radius: 25px\n"
"}")
        self.clear_btn.setCheckable(False)
        self.clear_btn.setObjectName("clear_btn")
        self.layoutWidget = QtWidgets.QWidget(Form)
        self.layoutWidget.setGeometry(QtCore.QRect(230, 220, 201, 167))
        self.layoutWidget.setObjectName("layoutWidget")
        self.formLayout = QtWidgets.QFormLayout(self.layoutWidget)
        self.formLayout.setContentsMargins(0, 0, 0, 0)
        self.formLayout.setVerticalSpacing(20)
        self.formLayout.setObjectName("formLayout")
        self.account_lable = QtWidgets.QLabel(self.layoutWidget)
        self.account_lable.setStyleSheet("color:rgb(0, 0, 103);\n"
"font: 10pt \"宋体\";")
        self.account_lable.setObjectName("account_lable")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.account_lable)
        self.account_edit = QtWidgets.QLineEdit(self.layoutWidget)
        self.account_edit.setStyleSheet("background-color:transparent;\n"
"border:none;\n"
"border-bottom: 1px solid black")
        self.account_edit.setClearButtonEnabled(True)
        self.account_edit.setObjectName("account_edit")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.account_edit)
        self.password_lable = QtWidgets.QLabel(self.layoutWidget)
        self.password_lable.setStyleSheet("color:rgb(0, 0, 103);\n"
"font: 10pt \"宋体\";")
        self.password_lable.setObjectName("password_lable")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.password_lable)
        self.password_edit = QtWidgets.QLineEdit(self.layoutWidget)
        self.password_edit.setStyleSheet("background-color:transparent;\n"
"border:none;\n"
"border-bottom: 1px solid black")
        self.password_edit.setClearButtonEnabled(True)
        self.password_edit.setObjectName("password_edit")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.password_edit)
        self.confirm_lable = QtWidgets.QLabel(self.layoutWidget)
        self.confirm_lable.setStyleSheet("color:rgb(0, 0, 103);\n"
"font: 10pt \"宋体\";")
        self.confirm_lable.setObjectName("confirm_lable")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.confirm_lable)
        self.confirm_edit = QtWidgets.QLineEdit(self.layoutWidget)
        self.confirm_edit.setStyleSheet("background-color:transparent;\n"
"border:none;\n"
"border-bottom: 1px solid black")
        self.confirm_edit.setClearButtonEnabled(True)
        self.confirm_edit.setObjectName("confirm_edit")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.confirm_edit)
        self.register_btn = QtWidgets.QPushButton(self.layoutWidget)
        self.register_btn.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.register_btn.sizePolicy().hasHeightForWidth())
        self.register_btn.setSizePolicy(sizePolicy)
        self.register_btn.setMinimumSize(QtCore.QSize(0, 45))
        self.register_btn.setStyleSheet("QPushButton {\n"
"    background-color: rgb(215, 255, 194);\n"
"    border-radius: 20px\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: rgb(215, 255, 194);\n"
"    border-radius: 20px\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: rgb(242, 255, 161);\n"
"    color:rgb(255, 255, 255);\n"
"    border-radius: 20px\n"
"}\n"
"\n"
"QPushButton.disabled {\n"
"    background-color: rgb(180, 180, 180);\n"
"    border-radius: 20px\n"
"}")
        self.register_btn.setObjectName("register_btn")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.register_btn)
        self.back_btn.raise_()
        self.about_btn.raise_()
        self.clear_btn.raise_()
        self.layoutWidget.raise_()
        self.main_menu_btn.raise_()

        self.retranslateUi(Form)
        self.main_menu_btn.clicked['bool'].connect(Form.show_hide_menu)
        self.about_btn.clicked.connect(Form.about)
        self.back_btn.clicked.connect(Form.back)
        self.clear_btn.clicked.connect(Form.clear)
        self.register_btn.clicked.connect(Form.check_register)
        self.account_edit.textChanged['QString'].connect(Form.enable_register_btn)
        self.password_edit.textChanged['QString'].connect(Form.enable_register_btn)
        self.confirm_edit.textChanged['QString'].connect(Form.enable_register_btn)
        QtCore.QMetaObject.connectSlotsByName(Form)
        Form.setTabOrder(self.account_edit, self.password_edit)
        Form.setTabOrder(self.password_edit, self.confirm_edit)
        Form.setTabOrder(self.confirm_edit, self.register_btn)
        Form.setTabOrder(self.register_btn, self.main_menu_btn)
        Form.setTabOrder(self.main_menu_btn, self.back_btn)
        Form.setTabOrder(self.back_btn, self.about_btn)
        Form.setTabOrder(self.about_btn, self.clear_btn)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.main_menu_btn.setText(_translate("Form", "菜单"))
        self.back_btn.setText(_translate("Form", "返回"))
        self.about_btn.setText(_translate("Form", "关于"))
        self.clear_btn.setText(_translate("Form", "重置"))
        self.account_lable.setText(_translate("Form", "账   号："))
        self.password_lable.setText(_translate("Form", "密   码："))
        self.confirm_lable.setText(_translate("Form", "确认密码："))
        self.register_btn.setText(_translate("Form", "注册"))
import images_rc
